### ISSUE TITLE
Question: WASM binary size

### ISSUE THREAD

**Issue by cometkim** [ocaml-wasm/wasm_of_ocaml#17]
Just curious,

I tried wasm_of_ocaml from an existing jsoo project. I got 2.5MB of jsoo build vs 3MB of wasm build for 24MB bytecode. (jsoo build can be reduced to 632kB through compression)

![image](https://github.com/ocaml-wasm/wasm_of_ocaml/assets/9696352/64eb13ef-16a1-443d-acbe-e9f68ac086cc)

Is it normal for wasm_of_ocaml builds to be large compared to jsoo? Or is there some optimization option I missed?

**Comment by cometkim** [comment]
Tried to reduce it using `wasm_opt` and it is now 2.8MB

**Comment by jmid** [comment]
I think some size increase is expected.
Here's another example from a recent presentation by @vouillon, of translating `ocamlc` with JSOO and `wasm_of_ocaml` and comparing their compressed and uncompressed output:
![filesize](https://github.com/ocaml-wasm/wasm_of_ocaml/assets/2655248/053716c8-e092-42be-b2b8-14678eaed9ef)

**Comment by vouillon** [comment]
Indeed, Wasm code is generally larger than JavaScript code. It compresses  a bit better, so the size difference is not as large when the files are compressed.

**Comment by cometkim** [comment]
Glad to learn something new. It's good to know that wasm can be compressed more.
