### ISSUE TITLE
[BUG] requested new array is too large

### ISSUE THREAD

**Issue by cometkim** [ocaml-wasm/wasm_of_ocaml#18]
**Describe the bug**

After a few modifications related to export functions, the build was successful, but the following error occurred when running the main code.

`Uncaught RuntimeError: requested new array is too large.`

![image](https://github.com/ocaml-wasm/wasm_of_ocaml/assets/9696352/585f309b-a6ff-4f4f-b664-3a06ac47945b)

I don't know where exactly the error is produced. I couldn't find any information searching in various places.

This is the source code https://github.com/rescript-lang/rescript-compiler/blob/master/jscomp/jsoo/jsoo_playground_main.ml and WASM the build I made using wasm_of_ocaml https://github.com/cometkim/rescript-wasm-test

**Expected behavior**

I expect it to have the same behavior as the existing jsoo build (which works pretty well). Then I can compare what (mostly performance) difference it actually makes.

To add more context, the module is used in the [ReScript](https://rescript-lang.org)'s playground. I guess this could be the ideal use case for WebAssembly + WebWorker.

**Versions**
- Chrome 119.0.6045.199 (It's failed to `WebAssembly.instantiate` in Node.js, so I'm testing it in Chrome)
- ocamlc 4.14.0
- js_of_ocaml (lib, compiler) 5.3.0
- wasm_of_ocaml-compiler 5.3.0-wasm
- wasm-merge (binaryen) 116

**Comment by vouillon** [comment]
I was expecting file descriptors to be small integers, so I'm storing some information in an array using them as an index. But `memfs` uses large integers (see streamich/memfs#607).
I'm going to fix that.

**Comment by vouillon** [comment]
I have pushes a fix.
