### ISSUE TITLE
[BUG] opam cannot install  wasm_of_ocaml-compiler

### ISSUE THREAD

**Issue by bentxt** [ocaml-wasm/wasm_of_ocaml#37]
**Describe the bug**

opam cannot install  wasm_of_ocaml-compiler

I try to run the following 3 lines as described in the Readme:
```
opam pin add dune.3.13 https://github.com/ocaml-wasm/dune.git#wasm
opam pin add -n --with-version 5.3.0-wasm .
opam install wasm_of_ocaml-compiler
```

For the last line I get the following error

```
...
$ opam install wasm_of_ocaml-compiler
[ERROR] No package named wasm_of_ocaml-compiler found.
```

**Versions**
Version of packages used to reproduce the bug

The OCaml compiler, version 4.14.0
Standard library directory: /Users/ben/.opam/4.14.0+flambda/lib/ocaml

**Comment by vouillon** [comment]
You need to clone the sources and execute `opam pin add -n --with-version 5.3.0-wasm .` from within the source directory. I should clarify the README...

**Comment by bentxt** [comment]
I created a small pull request under https://github.com/ocaml-wasm/wasm_of_ocaml/pull/39

**Comment by bentxt** [comment]
PR is merged
