### ISSUE TITLE
Link to here?

### ISSUE THREAD

**Issue by kripken** [ocaml-wasm/wasm_of_ocaml#7]
Hi @vouillon , I will be publishing a blogpost about WasmGC in a few weeks and I thought to perhaps include a mention of wasm_of_ocaml, if you think it's ready enough?

Specifically the post will have a few links for people looking to get started with WasmGC from various languages, brief mentions like "To get started compiling to WasmGC using `$LANGUAGE`, see `[link to their docs]`.

No worries if you don't want such a link at this time! But if you do let me know where to link to.

(sorry for posting here but I don't have a better way to reach you)

**Comment by vouillon** [comment]
Hi @kripken,
Yes, that would be great if you could mention wasm_of_ocaml.
For now, you can link to this repository.

**Comment by kripken** [comment]
Great, thanks, I'll add a mention and link to this repo.
