### ISSUE TITLE
Add wasm_of_ocaml to binaryen's "list of toolchains that use binaryen"?

### ISSUE THREAD

**Issue by TyOverby** [ocaml-wasm/wasm_of_ocaml#76]
I made this draft PR against binaryen: https://github.com/WebAssembly/binaryen/pull/6939

What do y'all think about un-drafting it and submitting it?

**Comment by OlivierNicole** [comment]
Sounds reasonable to me. Should we wait until wasmoo is released?

**Comment by vouillon** [comment]
That's a great idea. I don't think we should wait.

**Comment by TyOverby** [comment]
Great!  I've opened it for review, and added some details in the PR comment about how we use binarye (please leave a comment there if I got any of it wrong)
