### ISSUE TITLE
Installing wasm_of_ocaml became slower after adding binaryen in dependency 

### ISSUE THREAD

**Issue by wKich-octra** [ocaml-wasm/wasm_of_ocaml#98]
In this commit you added binaryen to deps https://github.com/ocaml-wasm/wasm_of_ocaml/commit/d3faed04608104798bd950e7532226ac3df0213b which is actually good thing.

But unfortunately installing ocaml deps step in Github Actions became slower from 4m to 17m and hangs too much time exactly on installing binaryen.bin package

## Before `d3faed0`
<img width="988" alt="Screenshot 2024-10-07 at 16 39 54" src="https://github.com/user-attachments/assets/fed283dd-57f9-4c7e-b11e-e2492ebfb21b">

## After `d3faed0`
<img width="971" alt="Screenshot 2024-10-07 at 16 40 50" src="https://github.com/user-attachments/assets/9d9e0bfa-227f-40c5-86a1-6e65050a7000">
<img width="631" alt="Screenshot 2024-10-07 at 16 41 27" src="https://github.com/user-attachments/assets/fa6b361a-56a2-4d42-8735-4176f9e51f43">

**Comment by wKich-octra** [comment]
To be honest, before this update I installed binaryen directly from github repo and it took 3s

<img width="1653" alt="Screenshot 2024-10-07 at 16 01 29" src="https://github.com/user-attachments/assets/1f7a2b48-d9f3-4d81-bd0f-9861b2ec3d38">

**Comment by wKich-octra** [comment]
Oh, I got it. You actually build binaryen https://github.com/ocaml/opam-repository/pull/26617

Will it be possible to use pre-built binaries instead of building from source code?

**Comment by vouillon** [comment]
Indeed, we are building binaryen. This makes it much easier to install wasm_of_ocaml, since we need a very recent version of binaryen, But indeed, that's a bit slow...

It might be possible to use pre-build binaries. It seems one package on opam does this: https://github.com/ocaml/opam-repository/tree/master/packages/libwasmtime.

It the meantime, you can pin an empty package:
https://github.com/ocaml-wasm/wasm_of_ocaml/blob/62fc9ed33b255ff1d504bc342b15a62db14408a2/.github/workflows/build-wasm_of_ocaml.yml#L134-L140

**Comment by jmid** [comment]
As a workaround, it might also work to 
- install the prebuilt-binaries as you did previously,
- then issue `opam install --fake binaryen-bin`
- finish the installation of `wasm_of_ocaml` as previously

The first step should put things in PATH.
The second step comes with the mandatory warning:
```
       --fake
           This option registers the actions into the opam database, without
           actually performing them. WARNING: This option is dangerous and
           likely to break your opam environment. You probably want --dry-run.
           You've been warned.
```
The third step should pick up the fake `binaryen-bin` as installed and work as long as the binaries are in PATH.

**Comment by wKich-octra** [comment]
@jmid it works. Thank you. You guys are doing awesome work.
